/**
 * Curated icon categories for the IconPicker.
 * All icon names are validated against the material-symbols package (v0.40.2).
 */
export const ICON_CATEGORIES: { label: string; icons: string[] }[] = [
  {
    label: 'Business & Office',
    icons: [
      'apartment', 'business_center', 'corporate_fare', 'domain', 'storefront',
      'factory', 'warehouse', 'store', 'work', 'badge', 'cases',
      'meeting_room', 'desk', 'chair', 'conveyor_belt', 'forklift',
      'precision_manufacturing', 'handyman', 'home_work', 'assignment',
      'inventory_2', 'receipt', 'task', 'event', 'schedule',
      'description', 'topic', 'folder', 'snippet_folder',
      'sticky_note_2', 'content_paste', 'fact_check', 'rule',
      'pending_actions', 'checklist', 'approval', 'how_to_vote',
    ],
  },
  {
    label: 'People & Social',
    icons: [
      'groups', 'group', 'person', 'handshake', 'diversity_3',
      'family_restroom', 'support_agent', 'record_voice_over',
      'sentiment_satisfied', 'volunteer_activism', 'communities', 'contacts',
      'supervisor_account', 'social_leaderboard', 'face', 'face_2',
      'face_3', 'face_4', 'face_5', 'face_6', 'elderly',
      'boy', 'girl', 'man', 'woman', 'group_work',
      'engineering', 'person_search', 'person_add', 'switch_account',
      'co_present', 'connect_without_contact', 'partner_exchange',
    ],
  },
  {
    label: 'Communication',
    icons: [
      'chat', 'mail', 'call', 'forum', 'send', 'inbox',
      'notifications', 'sms', 'voicemail', 'contact_mail',
      'contact_phone', 'mark_email_read', 'drafts', 'forward_to_inbox',
      'move_to_inbox', 'outgoing_mail', 'chat_bubble', 'comment',
      'feedback', 'rate_review', 'mark_chat_read', 'speaker_phone',
      'ring_volume', 'alternate_email', 'attach_email', 'hub',
      'cell_tower', 'question_mark',
    ],
  },
  {
    label: 'Tech & Engineering',
    icons: [
      'code', 'devices', 'cloud', 'terminal', 'memory', 'dns',
      'computer', 'monitor', 'tablet_android', 'developer_board',
      'data_object', 'api', 'bug_report', 'settings_ethernet',
      'cable', 'router', 'storage', 'database', 'cloud_upload',
      'cloud_download', 'language', 'webhook', 'integration_instructions',
      'code_blocks', 'deployed_code', 'data_array', 'build', 'token',
      'smart_toy', 'robot_2', 'neurology', 'genetics',
      'memory_alt', 'adb', 'sdk',
      'network_check', 'wifi', 'bluetooth', 'usb', 'lan',
      'device_hub', 'settings_input_component', 'electrical_services',
      'laptop_mac', 'laptop_chromebook', 'desktop_mac', 'desktop_windows',
      'keyboard', 'mouse', 'watch',
    ],
  },
  {
    label: 'Creative & Design',
    icons: [
      'palette', 'brush', 'design_services', 'draw', 'format_paint',
      'imagesearch_roller', 'gesture', 'texture', 'colorize',
      'gradient', 'style', 'architecture', 'view_in_ar', 'filter_vintage',
      'ink_pen', 'stylus', 'edit', 'auto_awesome_mosaic',
      'auto_awesome_motion', 'tune', 'crop',
      'straighten', 'transform', 'aspect_ratio', 'grid_on',
      'layers', 'animation', 'motion_photos_auto', 'panorama',
      'vignette', 'blur_on', 'hdr_strong', 'contrast',
    ],
  },
  {
    label: 'Media & Content',
    icons: [
      'movie', 'music_note', 'camera', 'videocam', 'mic',
      'headphones', 'photo_camera', 'image', 'slideshow',
      'podcasts', 'live_tv', 'play_circle', 'library_music',
      'radio', 'graphic_eq', 'theaters', 'newspaper',
      'article', 'edit_note', 'rss_feed', 'dynamic_feed', 'news',
      'video_library', 'photo_library', 'album',
      'audio_file', 'queue_music', 'music_video', 'surround_sound',
      'speaker', 'cast', 'connected_tv', 'display_settings',
      'video_call', 'video_settings', 'camera_roll', 'add_a_photo',
      'music_off', 'volume_up', 'equalizer',
    ],
  },
  {
    label: 'Marketing & Analytics',
    icons: [
      'campaign', 'ads_click', 'trending_up', 'analytics',
      'query_stats', 'monitoring', 'bar_chart', 'pie_chart',
      'show_chart', 'leaderboard', 'data_exploration', 'target',
      'track_changes', 'speed', 'ssid_chart', 'conversion_path',
      'web_traffic', 'stacked_bar_chart', 'waterfall_chart',
      'bubble_chart', 'scatter_plot', 'trending_down', 'trending_flat',
      'donut_large', 'donut_small', 'timeline', 'area_chart',
      'candlestick_chart', 'multiline_chart', 'table_chart',
      'pivot_table_chart', 'add_chart', 'insert_chart',
    ],
  },
  {
    label: 'Finance & Commerce',
    icons: [
      'account_balance', 'payments', 'savings', 'receipt_long',
      'attach_money', 'credit_card', 'account_balance_wallet',
      'currency_exchange', 'point_of_sale', 'shopping_cart',
      'shopping_bag', 'sell', 'local_atm', 'price_check',
      'money', 'request_quote', 'paid', 'finance',
      'credit_score', 'price_change', 'shopping_basket', 'toll',
      'wallet', 'money_bag', 'redeem', 'loyalty',
      'percent', 'calculate', 'assured_workload',
      'currency_bitcoin', 'currency_rupee', 'currency_pound',
      'currency_yen', 'euro',
    ],
  },
  {
    label: 'Health & Wellness',
    icons: [
      'local_hospital', 'favorite', 'spa', 'fitness_center',
      'medical_services', 'psychology', 'healing', 'health_and_safety',
      'medication', 'vaccines', 'monitor_heart', 'dentistry',
      'emergency', 'bloodtype', 'self_improvement', 'stethoscope',
      'cardiology', 'medical_information', 'health_metrics',
      'ecg_heart', 'acupuncture', 'pulmonology', 'lab_research',
      'self_care', 'local_pharmacy', 'biotech', 'clinical_notes',
      'vital_signs', 'body_system', 'rib_cage',
    ],
  },
  {
    label: 'Food & Drink',
    icons: [
      'restaurant', 'local_cafe', 'bakery_dining', 'lunch_dining',
      'wine_bar', 'local_bar', 'fastfood', 'ramen_dining',
      'icecream', 'cake', 'local_pizza', 'coffee', 'liquor',
      'set_meal', 'brunch_dining', 'tapas', 'breakfast_dining',
      'dinner_dining', 'kebab_dining', 'rice_bowl', 'soba',
      'egg', 'nutrition', 'cooking', 'stockpot', 'takeout_dining',
      'kitchen', 'outdoor_grill', 'skillet',
    ],
  },
  {
    label: 'Education & Science',
    icons: [
      'school', 'menu_book', 'science', 'history_edu',
      'auto_stories', 'library_books', 'psychology_alt',
      'lab_research', 'experiment', 'functions', 'translate', 'quiz',
      'model_training', 'book', 'import_contacts',
      'cast_for_education', 'backpack', 'calculate',
      'abc', 'spellcheck', 'grading',
      'local_library', 'award_star', 'workspace_premium',
      'military_tech',
    ],
  },
  {
    label: 'Travel & Transport',
    icons: [
      'flight', 'hotel', 'directions_car', 'local_shipping', 'sailing',
      'rocket_launch', 'train', 'directions_bus', 'two_wheeler',
      'electric_car', 'local_taxi', 'directions_boat', 'pedal_bike',
      'airport_shuttle', 'rv_hookup', 'moving', 'commute',
      'subway', 'tram', 'directions_railway', 'electric_scooter',
      'houseboat', 'snowmobile', 'agriculture', 'local_gas_station',
      'ev_station', 'tire_repair',
      'flight_takeoff', 'flight_land', 'connecting_airports',
      'luggage', 'no_luggage', 'travel_explore',
    ],
  },
  {
    label: 'Home & Real Estate',
    icons: [
      'home', 'cottage', 'villa', 'house', 'real_estate_agent',
      'location_city', 'holiday_village', 'foundation', 'roofing',
      'garage', 'fence', 'yard', 'deck', 'other_houses',
      'home_work', 'house_siding', 'garage_home',
      'home_and_garden', 'home_improvement_and_tools', 'door_front',
      'door_back', 'door_sliding', 'window', 'bedroom_parent',
      'living', 'bathtub', 'shower',
      'chair_alt', 'table_restaurant', 'bed', 'crib',
    ],
  },
  {
    label: 'Maps & Places',
    icons: [
      'map', 'explore', 'near_me', 'my_location',
      'location_on', 'pin_drop', 'add_location', 'edit_location',
      'wrong_location', 'share_location', 'person_pin_circle',
      'local_parking', 'local_gas_station', 'local_library',
      'local_pharmacy', 'local_fire_department', 'local_post_office',
      'local_laundry_service', 'local_mall', 'local_dining',
      'local_activity', 'directions', 'navigation', 'compass_calibration',
      'signpost', 'roundabout_right', 'traffic', 'satellite',
    ],
  },
  {
    label: 'Nature & Environment',
    icons: [
      'eco', 'park', 'forest', 'grass', 'water_drop',
      'energy_savings_leaf', 'compost', 'solar_power', 'wind_power',
      'landscape', 'pets', 'cruelty_free', 'agriculture', 'nature',
      'nature_people', 'landscape_2', 'energy', 'water',
      'waves', 'tsunami', 'volcano', 'public',
      'globe_asia', 'globe_uk', 'recycling',
      'garden_cart', 'nest_eco_leaf',
    ],
  },
  {
    label: 'Legal & Government',
    icons: [
      'gavel', 'balance', 'policy', 'shield', 'verified_user',
      'admin_panel_settings', 'security', 'local_police',
      'workspace_premium', 'how_to_reg',
      'lock', 'encrypted', 'privacy_tip', 'safety_check',
      'assured_workload', 'flag', 'flag_circle',
      'local_fire_department', 'sos', 'crisis_alert', 'release_alert',
    ],
  },
  {
    label: 'Sports & Recreation',
    icons: [
      'sports', 'sports_soccer', 'sports_basketball', 'sports_tennis',
      'sports_golf', 'sports_esports', 'pool', 'surfing',
      'skateboarding', 'snowboarding', 'hiking', 'kayaking',
      'sports_baseball', 'sports_cricket', 'sports_football',
      'sports_gymnastics', 'sports_handball', 'sports_hockey',
      'sports_kabaddi', 'sports_mma', 'sports_motorsports',
      'sports_rugby', 'sports_volleyball', 'scuba_diving',
      'paragliding', 'downhill_skiing', 'sledding', 'ice_skating',
      'rowing', 'scoreboard', 'trophy',
    ],
  },
  {
    label: 'Shapes & Symbols',
    icons: [
      'circle', 'square', 'hexagon', 'change_history', 'pentagon',
      'star', 'bolt', 'diamond', 'lightbulb', 'construction',
      'category', 'interests', 'extension', 'emoji_objects',
      'flare', 'whatshot', 'ac_unit', 'public', 'language',
      'globe', 'flag', 'bookmark', 'label', 'tag', 'keep',
      'key', 'lock', 'pin', 'favorite', 'heart_check',
      'thumb_up', 'thumb_down', 'stars',
      'dark_mode', 'wb_sunny', 'cloud', 'water_drop',
      'local_fire_department', 'spa', 'eco', 'recycling',
      'all_inclusive', 'gesture',
    ],
  },
  {
    label: 'Arrows & Navigation',
    icons: [
      'arrow_forward', 'arrow_back', 'arrow_upward', 'arrow_downward',
      'north', 'south', 'east', 'west', 'north_east', 'north_west',
      'south_east', 'south_west', 'swap_horiz', 'swap_vert',
      'compare_arrows', 'open_in_new', 'subdirectory_arrow_right',
      'redo', 'undo', 'reply', 'reply_all', 'forward',
      'trending_up', 'trending_down', 'trending_flat',
      'straight', 'turn_right', 'turn_left', 'merge',
    ],
  },
  {
    label: 'Weather & Time',
    icons: [
      'wb_sunny', 'cloud', 'thunderstorm', 'rainy', 'snowing',
      'schedule', 'timer', 'alarm', 'calendar_today', 'calendar_month',
      'event', 'date_range', 'hourglass',
      'hourglass_bottom', 'timelapse', 'update', 'history',
      'sunny', 'partly_cloudy_day', 'partly_cloudy_night',
      'foggy', 'ac_unit', 'thermostat',
      'air', 'humidity_percentage', 'dew_point', 'tornado',
      'tsunami', 'volcano', 'weather_mix',
    ],
  },
];

/** Flat set of all curated icon names for O(1) validation lookups */
export const VALID_ICONS = new Set(ICON_CATEGORIES.flatMap((c) => c.icons));

/** Flat array of all unique curated icon names */
export const ALL_ICONS = [...VALID_ICONS];
